name: Download and Commit File

on:
  workflow_dispatch:
  # You can also trigger on other events like push:
  # push:
  #   branches:
  #     - main

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download File
        run: |
          echo "Downloading file..."
          pwd
          mkdir -p data
          ls -l
          sh scripts/download.sh
          ls -l
          mv firehol_level1.netset data/firehol_level1.ipv4.netset

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f data/firehol_level1.ipv4.netset
          git commit -m "Add downloaded file"
          git push
