name: Download and Commit File

on:
  schedule:
    - cron: "*/5 * * * *"
  #    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download File
        run: |
          mkdir -p "$GITHUB_WORKSPACE/data"
          pwd
          echo "repo=$GITHUB_REPOSITORY"
          echo "work=$GITHUB_WORKSPACE"
          echo "====="
          ls -l $GITHUB_WORKSPACE
          echo "====="
          ls -l $GITHUB_WORKSPACE/data
          echo "====="
          sh scripts/download.sh
          echo "===="
          ls -l "$GITHUB_WORKSPACE/data"

      - name: Commit and Push
        run: |
          pwd
          echo "======"
          ls -l "$GITHUB_WORKSPACE/data"
          echo "======"
          git status --porcelain
          git_status=$(git status --porcelain)
          if [[ -n $git_status ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -f data/*
            git commit -m "Update downloaded file"
            git push
          fi
